/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocialNetwork.View;

import java.awt.event.ActionListener;
import java.awt.event.WindowListener;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author deferrari.exequiel
 */
public class SocialNetworkView extends javax.swing.JFrame {

    /**
     * Creates new form SocialNertworkView
     */
    public SocialNetworkView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuSocialNetwork = new javax.swing.JMenu();
        mnuPerfil = new javax.swing.JMenu();
        mnuPrivacidad = new javax.swing.JMenu();
        btnPrivacidad = new javax.swing.JMenuItem();
        menuConfiguracion = new javax.swing.JMenu();
        btnAgregarBoot = new javax.swing.JMenuItem();
        btnAmigos = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        btnAcercaDe = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 255, 255));

        mnuSocialNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/inicio.png"))); // NOI18N
        mnuSocialNetwork.setMnemonic('e');
        mnuSocialNetwork.setText("SocialNetwork");
        menuBar.add(mnuSocialNetwork);

        mnuPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/clientes.png"))); // NOI18N
        mnuPerfil.setMnemonic('h');
        mnuPerfil.setText("Perfil");
        menuBar.add(mnuPerfil);

        mnuPrivacidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/privacy.png"))); // NOI18N
        mnuPrivacidad.setText("Privacidad");

        btnPrivacidad.setText("Editar privacidad");
        btnPrivacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrivacidadActionPerformed(evt);
            }
        });
        mnuPrivacidad.add(btnPrivacidad);

        menuBar.add(mnuPrivacidad);

        menuConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/config.png"))); // NOI18N
        menuConfiguracion.setText("Configuracion");

        btnAgregarBoot.setText("Agregar Boot");
        menuConfiguracion.add(btnAgregarBoot);

        btnAmigos.setText("Amigos");
        menuConfiguracion.add(btnAmigos);

        menuBar.add(menuConfiguracion);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/ayudaX18.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");

        btnAcercaDe.setText("Acerca de...");
        mnuAyuda.add(btnAcercaDe);

        menuBar.add(mnuAyuda);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/salir-sistema.png"))); // NOI18N
        mnuSalir.setText("Salir");
        menuBar.add(mnuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrivacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrivacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrivacidadActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SocialNetworkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SocialNetworkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SocialNetworkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SocialNetworkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SocialNetworkView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAcercaDe;
    private javax.swing.JMenuItem btnAgregarBoot;
    private javax.swing.JMenuItem btnAmigos;
    private javax.swing.JMenuItem btnPrivacidad;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConfiguracion;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuPerfil;
    private javax.swing.JMenu mnuPrivacidad;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuSocialNetwork;
    // End of variables declaration//GEN-END:variables

    public void windowListener(WindowListener listen){
        this.addWindowListener(listen);
    }
        
    public void actionListener(ActionListener listen){
        btnAgregarBoot.addActionListener(listen);
        btnAcercaDe.addActionListener(listen);
        btnAmigos.addActionListener(listen);
        btnPrivacidad.addActionListener(listen);
        btnAgregarBoot.addActionListener(listen);
    }

    public JMenuItem getBtnAcercaDe() {
        return btnAcercaDe;
    }

    public void setBtnAcercaDe(JMenuItem btnAcercaDe) {
        this.btnAcercaDe = btnAcercaDe;
    }

    public JMenuItem getBtnAgregarBoot() {
        return btnAgregarBoot;
    }

    public void setBtnAgregarBoot(JMenuItem btnAgregarBoot) {
        this.btnAgregarBoot = btnAgregarBoot;
    }

    public JMenuItem getBtnAmigos() {
        return btnAmigos;
    }

    public void setBtnAmigos(JMenuItem btnAmigos) {
        this.btnAmigos = btnAmigos;
    }

    public JMenuItem getBtnPrivacidad() {
        return btnPrivacidad;
    }

    public void setBtnPrivacidad(JMenuItem btnPrivacidad) {
        this.btnPrivacidad = btnPrivacidad;
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    public JMenu getMenuConfiguracion() {
        return menuConfiguracion;
    }

    public void setMenuConfiguracion(JMenu menuConfiguracion) {
        this.menuConfiguracion = menuConfiguracion;
    }

    public JMenu getMnuAyuda() {
        return mnuAyuda;
    }

    public void setMnuAyuda(JMenu mnuAyuda) {
        this.mnuAyuda = mnuAyuda;
    }

    public JMenu getMnuPerfil() {
        return mnuPerfil;
    }

    public void setMnuPerfil(JMenu mnuPerfil) {
        this.mnuPerfil = mnuPerfil;
    }

    public JMenu getMnuPrivacidad() {
        return mnuPrivacidad;
    }

    public void setMnuPrivacidad(JMenu mnuPrivacidad) {
        this.mnuPrivacidad = mnuPrivacidad;
    }

    public JMenu getMnuSalir() {
        return mnuSalir;
    }

    public void setMnuSalir(JMenu mnuSalir) {
        this.mnuSalir = mnuSalir;
    }

    public JMenu getMnuSocialNetwork() {
        return mnuSocialNetwork;
    }

    public void setMnuSocialNetwork(JMenu mnuSocialNetwork) {
        this.mnuSocialNetwork = mnuSocialNetwork;
    }
    
   
}
